<?php

/**
 * @file
 * Tide API module functionality.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\jsonapi\Routing\Routes;

/**
 * Implements hook_entity_access().
 */
function tide_api_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity->getEntityTypeId() == 'menu' || $entity->getEntityTypeId() == 'menu_link_content') {
    if ($operation == 'view') {
      if (Routes::isJsonApiRequest(\Drupal::request()->attributes->all())) {
        return AccessResult::allowed()->cachePerUser();
      }
    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_jsonapi_ENTITY_TYPE_filter_access().
 */
function tide_api_jsonapi_menu_link_content_filter_access(EntityTypeInterface $entity_type, AccountInterface $account) {
  return [
    JSONAPI_FILTER_AMONG_ALL => AccessResult::allowed()->cachePerPermissions(),
  ];
}

/**
 * Implements hook_jsonapi_ENTITY_TYPE_filter_access().
 */
function tide_api_jsonapi_menu_filter_access(EntityTypeInterface $entity_type, AccountInterface $account) {
  return [
    JSONAPI_FILTER_AMONG_ALL => AccessResult::allowed()->cachePerPermissions(),
  ];
}
